name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs: 
  web-deploy:
    name: Deploy latest commit
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci

      - name: Build app
        run: npm run build

      - name: Convert PEM to OpenSSH format and encrypt with passphrase
        run: |
          openssl rsa -in ./.ssh_key/Production-server.pem -outform PEM -out private_key.pem -passin pass:"{{ secrets.PASS }}"
        env:
          PASSPHRASE: ${{ secrets.PASS }}

      - name: Deploy to cPanel via SSH
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SERVER }}
          remote-user:  ${{ secrets.SSH_USERNAME }}
          ssh-port: ${{ secrets.SSH_PORT }}
          private-ssh-key: ./private_key.pem
          destination-path: ~/adm.aremxyplug.com/
          source-path: ./.next/

         
